sudo: false

language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"

install:
    - pip install --upgrade setuptools coveralls

script:
    - coverage run --branch --include="terminal_address/*" setup.py test

after_success:
    - coveralls

notifications:
    email: false
